took the config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,26 +1,71 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/configuration-reference/#jobs
+workflows:
+  version: 2
+  test-commit-build-deploy:
+    jobs:
+      - tests
+      - commit:
+          requires:
+            - tests
+      - build:
+          requires:
+            - commit
+      - deploy:
+          requires:
+            - build
+
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/configuration-reference/#executor-job
+  tests:
     docker:
-      - image: cimg/base:stable
-    # Add steps to the job
-    # See: https://circleci.com/docs/configuration-reference/#steps
+      - image: circleci/python:3.10
     steps:
       - checkout
+      # Add your test steps here
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Install dependencies and run tests
+          command: |
+            echo "Installing dependencies..."
+            pip install -r requirements.txt
+            python manage.py test lorenzo_barone | tee test-results.txt
+            test_result=$?
+            if [ $test_result -ne 0 ]; then
+              echo "Tests failed. Halting pipeline..."
+              circleci step halt
+            fi
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/configuration-reference/#workflows
-workflows:
-  say-hello-workflow:
-    jobs:
-      - say-hello
+  commit:
+    docker:
+      - image: circleci/python:3.10
+    steps:
+      - checkout
+      # Add your commit steps here
+      - run:
+          name: Commit changes
+          command: |
+            echo "Committing changes..."
+            # Insert your commit commands here
+
+  build:
+    docker:
+      - image: circleci/python:3.10
+    steps:
+      - checkout
+      # Add your build steps here
+      - run:
+          name: Build and test
+          command: |
+            echo "Building and testing..."
+            # Insert your build and test commands here
+
+  deploy:
+    docker:
+      - image: circleci/python:3.10
+    steps:
+      - checkout
+      # Add your deployment steps here
+      - run:
+          name: Deploy to production
+          command: |
+            echo "Deploying to production..."
+            # Insert your deployment commands here
